<a href="https://colab.research.google.com/github/strbrr7/dataML_course/blob/main/HW_2_2_%D0%9C%D0%B0%D1%82%D0%B5%D0%BC%D0%B0%D1%82%D0%B8%D1%87%D0%BD%D0%B5_%D1%84%D0%BE%D1%80%D0%BC%D1%83%D0%BB%D1%8E%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F_%D0%BB%D0%BE%D0%B3%D1%96%D1%81%D1%82%D0%B8%D1%87%D0%BD%D0%BE%D1%97_%D1%80%D0%B5%D0%B3%D1%80%D0%B5%D1%81%D1%96%D1%97.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

В цьому домашньому завданні ми реалізуємо логістичну регресію на `numpy`.
Ці завдання допоможуть вам ґрунтовно засвоїти основні концепції логістичної регресії та реалізувати їх на практиці 🔥

#### Завдання 1: Реалізація функції сигмоїди
1. З використанням `numpy` напишіть функцію `sigmoid(z)` для обчислення значення сигмоїди згідно з формулою:
   $$
   \sigma(z) = \frac{1}{1 + e^{-z}}
   $$
2. Використовуючи цю функцію, обчисліть значення сигмоїди для наступних даних: $ z = [-2, -1, 0, 1, 2] $. Виведіть результат обчислень.


In [177]:
import numpy as np

In [178]:
def sigmoid(z):
  sigmoid = 1 / (1 + np.exp(-z))
  return sigmoid

In [179]:
numbers = [-2, -1, 0, 1, 2]

for num in numbers:
  value = sigmoid(num)
  print(f'For {num} sigmoid is {value:4f}')

For -2 sigmoid is 0.119203
For -1 sigmoid is 0.268941
For 0 sigmoid is 0.500000
For 1 sigmoid is 0.731059
For 2 sigmoid is 0.880797




#### Завдання 2: Реалізація функції гіпотези для логістичної регресії
1. Напишіть функцію `hypothesis(theta, X)`, яка обчислює гіпотезу для логістичної регресії, використовуючи функцію сигмоїди. Формула гіпотези:
   $$
   h_\theta(x) = \sigma(\theta^T x) = \frac{1}{1 + e^{-\theta^T x}}
   $$
2. Використайте функцію `hypothesis` для обчислення значень гіпотези для наступних даних:
   
   $\theta = [0.5, -0.5]$
   
   $X = \begin{bmatrix} 1 & 2 \\ 1 & -1 \\ 1 & 0 \\ 1 & 1 \end{bmatrix}$

  Виведіть результат обчислень.


In [180]:
theta = np.array([[0.5, 0.5]])

In [181]:
X = np.array([[1, 2],
             [1, -1],
             [1, 0],
             [1, 1]])

In [182]:
def hypothesis(theta, X):
  hypothesis = sigmoid(np.dot(X, theta.T))
  return hypothesis

In [183]:
hypothesis(theta, X)

array([[0.81757448],
       [0.5       ],
       [0.62245933],
       [0.73105858]])

#### Завдання 3: Реалізація функції для підрахунку градієнтів фукнції втрат
1. Напишіть функцію `compute_gradient(theta, X, y)`, яка обчислює градієнти функції втрат для логістичної регресії. Формула для обчислення градієнта:
   $$
   \frac{\partial L(\theta)}{\partial \theta_j} = \frac{1}{m} \sum_{i=1}^{m} \left[ (h_\theta(x^{(i)}) - y^{(i)}) x_j^{(i)} \right]
   $$
2. Використайте функцію `compute_gradient` для обчислення градієнтів для наступних даних:

  $\theta = [0.5, -0.5]$

  $X = \begin{bmatrix} 1 & 2 \\ 1 & -1 \\ 1 & 0 \\ 1 & 1 \end{bmatrix}$

  $y = [1, 0, 1, 0]$

  Виведіть результат обчислень.

In [184]:
y = [[1, 0, 1, 0]]

In [185]:
def compute_gradient(theta, X, y):
  gradient = (1 / len(X)) * sum((hypothesis(theta, X) - y).dot(X))
  return gradient

In [186]:
compute_gradient(theta, X, y)

array([ 0.67109239, -0.66445381])


#### Завдання 4: Реалізація повного батч градієнтного спуску

**Задача:**
1. Напишіть функцію `full_batch_gradient_descent(X, y, lr=0.1, epochs=100)`, яка реалізує алгоритм Full градієнтного спуску для логістичної регресії. Використовуйте такі формули:
   - Гіпотеза: $ h_\theta(x) = \sigma(\theta^T x) $
   - Оновлення параметрів: $ \theta_j := \theta_j - \alpha \frac{\partial L(\theta)}{\partial \theta_j} $
2. Використайте функцію `full_batch_gradient_descent` для обчислення параметрів моделі на наступних даних:

  $X = \begin{bmatrix} 1 & 2 \\ 1 & -1 \\ 1 & 0 \\ 1 & 1 \end{bmatrix}$

  $y = [1, 0, 1, 0]$

  Увага! Матриця $X$ вже має стовпець одиниць і передбачається, що це. - стовпець для intercept - параметра зсуву.

  Виведіть результат обчислень.


In [187]:
def full_batch_gradient_descent(X, y, lr=0.1, epochs=100):
  theta = np.array([0.0, 0.0])
  n = len(y)
  for _ in range(epochs):
    gradient = compute_gradient(theta, X, y)
    theta -= lr * gradient
  return theta


In [196]:
theta_full_batch = full_batch_gradient_descent(X, y, lr=0.1, epochs=100)

#### Завдання 5. Обчислення точності моделі

1. Напишіть функцію `predict_proba(theta, X)`, яка використовує знайдені параметри $\theta$ для обчислення ймовірностей належності поточного прикладу з даних до класу $y=1$ на основі значень $\sigma(\theta^T x)$.

2. Напишіть функцію `predict(theta, X, threshold=0.5)`, яка обчислює клас з передбаченої імовірності належності екземпляра до класу 1 з порогом 0.5. Тобто якщо ймовірність менше 0.5, то передбачаємо клас 0, інакше клас 1.

3. Напишіть функцію `accuracy(y_true, y_pred)`, яка обчислює точність моделі, визначивши частку правильно передбачених класів.

  Формула метрики Accuracy:
  $$
  \text{Accuracy} = \frac{\sum_{i=1}^{m} I(\hat{{y}^{(i)}} = y^{(i)})}{m}
  $$

  де $\hat{{y}^{(i)}}$ - передбачене значення класу, $I$ - індикаторна функція (яка дорівнює 1, якщо умова виконується, і 0 - якщо ні), $m$ - кількість прикладів.

4. Обчисліть з використанням даних в завданні 4 $X$, $y$ та обчислених коефіцієнтах $\theta$ та виведіть на екран:
  - передбачені моделлю імовірності належності кожного з екземплярів в матриці `X` до класу 1
  - класи кожного екземпляра з матриці `X`
  - точність моделі.

In [189]:
def predict_proba(theta, X):
  z = np.dot(X, theta.T)
  value = sigmoid(z)
  return value


In [190]:
predict_proba(theta, X)

array([[0.81757448],
       [0.5       ],
       [0.62245933],
       [0.73105858]])

In [191]:
def predict(theta, X, threshold=0.5):
  z = np.dot(X, theta.T)
  value = sigmoid(z)
  y_pred = (value > threshold).astype(int)
  return y_pred

In [192]:
y_pred = predict(theta, X, threshold=0.5)


In [212]:
def accuracy(y_true, y_pred):
  accuracy = (y_pred == y_true).astype(bool) # напевно можна було б обійтись типом int, мені здається через bool більш зрозуміло
  return accuracy

In [213]:
accuracy_prediction = accuracy(y, y_pred.T)
accuracy_prediction

array([[ True,  True,  True, False]])

In [214]:
prediction = predict_proba(theta_full_batch, X)
display(prediction)

array([0.77966809, 0.25617965, 0.42815828, 0.61944235])

In [215]:
class_of_prediction = predict(theta_full_batch, X, threshold=0.5)
display(class_of_prediction)

array([1, 0, 0, 1])

In [216]:
accuracy_full_batch = accuracy(y, class_of_prediction)
display(accuracy_full_batch)

array([[ True,  True, False, False]])