<a href="https://colab.research.google.com/github/strbrr7/dataML_course/blob/main/MY_HW_2_1_%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%96_%D1%96_%D0%B2%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B8_(%D0%B2%D1%81%D1%82%D1%83%D0%BF_%D0%B4%D0%BE_%D0%BB%D1%96%D0%BD_%D0%B0%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B8).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [203]:
import numpy as np

In [204]:
vector = np.array(np.random.rand(1, 10))

In [205]:
? np.random.rand

In [206]:
matrix = np.array([[11,14,17],
                   [20,23,26],
                   [29,32,35]])

In [207]:
vector, vector.shape

(array([[0.20068594, 0.52305883, 0.19672175, 0.04356177, 0.69647059,
         0.0838059 , 0.89903373, 0.44929489, 0.83238422, 0.59030896]]),
 (1, 10))

In [208]:
matrix, matrix.shape

(array([[11, 14, 17],
        [20, 23, 26],
        [29, 32, 35]]),
 (3, 3))


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [209]:
vector_10 = np.full_like(10, 10)

In [210]:
type(vector), type(vector_10)

(numpy.ndarray, numpy.ndarray)

In [230]:
vector = np.round(vector + vector_10, decimals=2)

In [231]:
vector

array([[20.2 ],
       [20.52],
       [20.2 ],
       [20.04],
       [20.7 ],
       [20.08],
       [20.9 ],
       [20.45],
       [20.83],
       [20.59]])

In [213]:
matrix = 2 * matrix

In [214]:
? np.round

In [232]:
vector_square = np.square(vector)

In [233]:
vector_square

array([[408.04  ],
       [421.0704],
       [408.04  ],
       [401.6016],
       [428.49  ],
       [403.2064],
       [436.81  ],
       [418.2025],
       [433.8889],
       [423.9481]])


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [217]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])
A = A.T

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])
B = B.T

C = np.array([[0],
              [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.75, 0.35],
       [0.53, 0.47, 0.21]])

array([[0.17, 0.38],
       [0.58, 0.11],
       [0.75, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [218]:
result_matrix = np.dot(A, B)

In [219]:
result_matrix, result_matrix.shape

(array([[0.7281, 0.2034],
        [0.5202, 0.2846]]),
 (2, 2))

Якщо ми домножимо `result_matrix`розмірністю 2х2 на `С` розмірністю 2х1, то вийде матриця розмірністю 2х1

In [220]:
rm_mult_c = np.dot(result_matrix, C)

In [221]:
rm_mult_c

array([[0.2034],
       [0.2846]])

Якщо ми домножимо result_matrixрозмірністю 2х1 на D розмірністю 2х2, то вийде матриця розмірністю 2х2

In [222]:
rm_mult_d = np.dot(result_matrix, D)

In [223]:
rm_mult_d

array([[0.2034, 0.7281],
       [0.2846, 0.5202]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [224]:
result_matrix.T

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

In [239]:
vector = vector.T

In [235]:
vector

array([[20.2 , 20.52, 20.2 , 20.04, 20.7 , 20.08, 20.9 , 20.45, 20.83,
        20.59]])

Зміни є, тепер в нас вектор-рядок замість вектор-стовпця

In [236]:
column_vector = np.expand_dims(vector, axis=1)

In [237]:
column_vector

array([[[20.2 , 20.52, 20.2 , 20.04, 20.7 , 20.08, 20.9 , 20.45, 20.83,
         20.59]]])

В нас збільшиласть к-сть квадратних дужок. Напевно збільнилась вимірність

In [238]:
column_vector.T, column_vector.shape

(array([[[20.2 ]],
 
        [[20.52]],
 
        [[20.2 ]],
 
        [[20.04]],
 
        [[20.7 ]],
 
        [[20.08]],
 
        [[20.9 ]],
 
        [[20.45]],
 
        [[20.83]],
 
        [[20.59]]]),
 (1, 1, 10))